title: Student-Blog
description: "Blog of a Computer Science Student"
author:
  name: "Fırat"
  email: "firatolcay1999@gmail.com"
  url: "https://firatfolcay.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Firat Fuat Olcay"
year : "2019"
